### ISSUE TITLE
Live demo duplication

### ISSUE THREAD

**Issue by jtolio** [google/git-appraise-web#10]
Just out of curiosity, I see a lot of comment duplication (comments left twice) in the live demo. What caused that? Is that likely to happen if we adopt this?

**Comment by ojarjur** [comment]
Short answer: no, this shouldn't be an issue for you.

Longer answer:

The duplicate comments were written by the [pull-request mirror](https://github.com/google/git-pull-request-mirror), and were caused by a change to the text of the comments that started showing up on December 19.

There are two differences in the text between the two instances of each comment:

1. Whether newlines are represented by "\n" or "\r\n"
2. Whether or not they have a trailing newline

When I updated the mirror in December, that triggered it to go back through all of the open reviews to look for new comments. It saw the comments with this new pattern, and since their text was changed, it interpreted the comments as being new and wrote them out to the repository (causing them to be duplicated).

Note that the change didn't necessarily happen on the 19th; that's just when I restarted the mirror and triggered it to look back at the open reviews.

I *believe* what caused the text to change was some change to the GitHub API, but I haven't been able to find any docs for such a change, so I may be wrong about that.

Regardless, this seems to have been a one-time event, so I don't think you need to worry about it.
